# Generated by Django 3.1.7 on 2021-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
