# Generated by Django 3.1.7 on 2021-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='altura',
            field=models.FloatField(blank='true'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_de_diagnostico',
            field=models.DateField(blank='true'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_de_nascimento',
            field=models.DateField(blank='true'),
        ),
    ]
