# Generated by Django 3.1.7 on 2021-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20210503_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='altura',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_de_diagnostico',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_de_nascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='peso',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
