# Generated by Django 3.1.7 on 2021-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20210503_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_de_diagnostico',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
