# Generated by Django 3.1.7 on 2021-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('maos', models.IntegerField()),
                ('pes', models.IntegerField()),
                ('punhos', models.IntegerField()),
                ('cotovelos', models.IntegerField()),
                ('joelhos', models.IntegerField()),
                ('tornozelos', models.IntegerField()),
                ('ombros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('sentimento_comeco_do_dia', models.TextField(blank='true', max_length=30)),
                ('sentimento_fim_do_dia', models.TextField(blank='true', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Remedios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_remedio', models.TextField(max_length=100)),
                ('frequencia_semanal_do_remedio', models.TextField(max_length=100)),
                ('frequencia_diaria_do_remedio', models.IntegerField()),
                ('horario_primeira_dose', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rigidez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('rigidez_matinal', models.IntegerField()),
            ],
        ),
    ]
