# Generated by Django 3.1.7 on 2021-05-03 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rigidez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('rigidez_matinal', models.IntegerField(blank='true', default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remedios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('nome_do_remedio', models.TextField(blank='true', max_length=100)),
                ('frequencia_semanal_do_remedio', models.TextField(blank='true', max_length=100)),
                ('frequencia_diaria_do_remedio', models.IntegerField(blank='true')),
                ('horario_primeira_dose', models.TimeField(blank='true')),
                ('data_de_inicio', models.DateField(blank='true')),
                ('dosagem', models.FloatField(blank='true')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('sentimento_comeco_do_dia', models.TextField(blank='true', max_length=30)),
                ('sentimento_fim_do_dia', models.TextField(blank='true', max_length=30)),
                ('ansiedade', models.IntegerField(blank='true')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now=True)),
                ('maos', models.IntegerField(blank='true', default=0)),
                ('pes', models.IntegerField(blank='true', default=0)),
                ('punhos', models.IntegerField(blank='true', default=0)),
                ('cotovelos', models.IntegerField(blank='true', default=0)),
                ('joelhos', models.IntegerField(blank='true', default=0)),
                ('tornozelos', models.IntegerField(blank='true', default=0)),
                ('ombros', models.IntegerField(blank='true', default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
