# Generated by Django 3.1.7 on 2021-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_reumatico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='humor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='remedios',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rigidez',
            name='id',
        ),
        migrations.AddField(
            model_name='humor',
            name='ansiedade',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AddField(
            model_name='remedios',
            name='dia',
            field=models.DateField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dor',
            name='cotovelos',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='dor',
            name='dia',
            field=models.DateField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dor',
            name='joelhos',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='dor',
            name='maos',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='dor',
            name='ombros',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='dor',
            name='pes',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='dor',
            name='punhos',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='dor',
            name='tornozelos',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='humor',
            name='dia',
            field=models.DateField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remedios',
            name='frequencia_diaria_do_remedio',
            field=models.IntegerField(blank='true', default=0),
        ),
        migrations.AlterField(
            model_name='remedios',
            name='frequencia_semanal_do_remedio',
            field=models.TextField(blank='true', max_length=100),
        ),
        migrations.AlterField(
            model_name='remedios',
            name='horario_primeira_dose',
            field=models.TimeField(blank='true'),
        ),
        migrations.AlterField(
            model_name='remedios',
            name='nome_do_remedio',
            field=models.TextField(blank='true', max_length=100),
        ),
        migrations.AlterField(
            model_name='rigidez',
            name='dia',
            field=models.DateField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rigidez',
            name='rigidez_matinal',
            field=models.IntegerField(blank='true', default=0),
        ),
    ]
